# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 steredbits and Pelagia contributors
# Generates a C++ file containing the fonts as byte arrays.
# Usage: cmake -DOUT=<file.cpp> -DREGULAR=<ttf> -DBOLD=<ttf> -P embed_fonts.cmake

function(append_array var_name path out_var)
    file(READ "${path}" hex HEX)
    file(SIZE "${path}" size)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    # About 24 bytes per line to keep the file readable.
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){24})" "\\1\n    " bytes "${bytes}")
    set(${out_var} "${${out_var}}const unsigned char ${var_name}[] = {\n    ${bytes}\n};\nconst size_t ${var_name}Size = ${size};\n\n" PARENT_SCOPE)
endfunction()

set(content "// File generated by cmake/embed_fonts.cmake: do not edit.\n#include \"ui/embedded_fonts.h\"\n\nnamespace ui {\n\n")
append_array(kNotoSansRegular "${REGULAR}" content)
append_array(kNotoSansBold "${BOLD}" content)
string(APPEND content "}  // namespace ui\n")
file(WRITE "${OUT}.tmp" "${content}")
file(COPY_FILE "${OUT}.tmp" "${OUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUT}.tmp")
